name: deploy_backend

on: 
    push:
        branches: [ main ]
        paths:
        - 'backend/**'

env:
  AZURE_WEBAPP_NAME: GetVisitorCounts    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'backend'      # set this to the path to your web app project, defaults to the repository root
  NUGET_VERSION: '7.0'           # set this to the dot net version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    -   name: 'Checkout Github Action'
        uses: actions/checkout@v3

    -   name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CRESIDENTIALS }}
    
    - name: Setup DotNet ${{ env.DOTNET_VERSION  }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION}}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/backend/api'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run unit test'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/backend/tests'
        dotnet test
  
    - name: 'Run Azure Function Action'
      uses: Azure/functions-action@v1
      id: fa
      with: 
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }} # Replace with your app name
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api/output/'